### ISSUE TITLE
Current build/examples break:  Uncaught TypeError: Cannot set property 'Ending' of undefined

### ISSUE THREAD

**Issue by shaunakv1** [HamHamFonFon/ol3-drawButtons#4]
The current release and code at master breaks with error even in examples: 

ol3-controldrawfeatures.js:28 Uncaught TypeError: Cannot set property 'Ending' of undefined

```
Uncaught TypeError: Cannot set property 'Ending' of undefined
    at new ol.control.ControlDrawFeatures (ol3-controldrawfeatures.js:24)
    at ol3-controldrawfeatures.js:515
    at ol3-controldrawfeatures.js:10
    at ol3-controldrawfeatures.js:12
```

It seems that invoking the control , no longer passes the arguments back to the constructor.

**Comment by Astro-Otter-Space** [comment]
Hello, 

Unfortunatly I have no time to spend on the plugin in this moment :( . Sorry for the bugs but if you have a solution, i will be happy to merge your fix with a pull request :).
