### ISSUE TITLE
limit drawn features

### ISSUE THREAD

**Issue by geopamplona** [HamHamFonFon/ol3-drawButtons#5]
good afternoon
I'm using your library; is very interesting, I was developing the same last months .. now I use your library ... it is practical and simple

my question is simple, I need to limit the number of features that can be drawn, is there a functionality about this?

thank you very much !

**Comment by Astro-Otter-Space** [comment]
Hello,

Thank you to your support :).
However, there isn't this functionnality. But if you think it will be interesting to have it, you can develop and make a pull request :).
